language: node_js
sudo: required
node_js:
  - "10"
cache: yarn
jobs:
  include:
    - stage: Lint
      script: yarn test:lint
    - stage: Build and Deploy
      script: yarn build && yarn deploy
env:
  global:
    - REPO="git@github.com:quipucords/quipudocs"
    - AUTO_DEPLOY=true
    - BRANCH="dev"
    - EMAIL="quipucords@redhat.com"
    - USER="Quipucords CI"
